version: '3'

services:
  loginserver:
    build: .
    command: bash -c "cd login && make && loginserver"
    volumes:
      - ./login:/usr/src/l2auth/login
    ports:
      - 2106:2106
  gameserver:
    build: .
    command: bash -c "cd game/src && make && cd ../lib && make clean && make && cd .. && build/gameserver"
    volumes:
      - ./game:/usr/src/l2auth/game
    ports:
      - 7777:7777
