version: '3'

services:
  loginserver:
    build: .
    command: bash -c "cd login && make && build/loginserver"
    ports:
      - "2106:2106"
  gameserver:
    build: .
    command: bash -c "cd game/src && make && cd ../lib && make clean && make && cd .. && build/gameserver"
    volumes:
      - ".:/usr/src/l2auth"
    ports:
      - "7777:7777"
